### PR TITLE
Update to 3.7.6. with neetle 3.7

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
cc @leofang

**Comment by hmaarrfk** [comment]
See https://gitlab.com/gnutls/gnutls/-/issues/660

**Comment by hmaarrfk** [comment]
@conda-forge/gnutls this is ready for review.

**Comment by leofang** [comment]
Thanks Mark! Quick question, it seems Travis is back now, perhaps you can switch back for aarch64/ppc64le to speed up the test?

**Comment by hmaarrfk** [comment]
Potentially, let me just get this patch. I didn't like ignoring the run exports.

**Comment by hmaarrfk** [comment]
Well its faster, but it is still close to the timeout of 1 hour, so it makes me uneasy, anyway, this is ready for review.

**Comment by leofang** [comment]
@hmaarrfk thanks! FYI you may want to restart the ppc64le build, it timed out on master.

**Comment by hmaarrfk** [comment]
Thanks

**Comment by hmaarrfk** [comment]
Please open a PR moving to azure if this happens again. likely bumping the build number  too.

**Comment by leofang** [comment]
Yeah sometimes we see timeouts too, very often like this one that it works mostly fine in PRs but not when merged to master. If we retry one or two more times it usually resolves. If not then it's better to switch back.

**Comment by hmaarrfk** [comment]
i guess i don't care to monitor things if they work on azure.

Typically emulation fails due to time constraints, or bad instructions. Since we don't have either, i'm going to rebuild on azure.

**Pull request merged**
